title: PSAP
description: Performance and Scale for AI Platforms — making Red Hat AI the most performant and scalable enterprise AI platform for Gen AI applications
url: https://openshift-psap.github.io
github:
  source:
    branch: master

plugins:
  - jekyll-github-metadata
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
    values:
      layout: default
